/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seatarrangement;

import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author vishnu
 */
public class Pannel3 extends javax.swing.JPanel {
    String[] rooms=new String[20];
    String[] dept=new String[15];
    int[][] arrange=new int[500][10];
    int n,m,flag;
    int bench;
/**
     * Creates new form Pannel3
     */
    public Pannel3() {
        initComponents();
    }
    //To Store selected check box values
    public void select(){
    int i=0;
        if(c1.isSelected()){
            rooms[i]="411";
            i++;
        }if(c2.isSelected()){
            rooms[i]="412";
            i++;
        }if(c3.isSelected()){
            rooms[i]="413";
            i++;
        }if(c4.isSelected()){
            rooms[i]="422";
            i++;
        }if(c5.isSelected()){
            rooms[i]="202";
            i++;
        }if(c6.isSelected()){
            rooms[i]="201";
            i++;
        }if(c7.isSelected()){
            rooms[i]="601";
            i++;
        }if(c8.isSelected()){
            rooms[i]="603";
            i++;
        }
        if(c9.isSelected()){
            rooms[i]="604";
            i++;
        }
        if(c10.isSelected()){
            rooms[i]="605";
            i++;
        }
        if(c11.isSelected()){
            rooms[i]="Drawing hall";
            i++;
        }
        n=i;
        for(i=0;i<n;i++){
            System.out.println(rooms[i]);
        }
        
        i=0;
        if(y1.isSelected()){
            dept[i]="S1CS";
            i++;
        }if(y2.isSelected()){
            dept[i]="S1EC";
            i++;
        }if(y3.isSelected()){
            dept[i]="S1EEE";
            i++;
        }
        if(y4.isSelected()){
            dept[i]="S3CS";
            i++;
        }
        if(y5.isSelected()){
            dept[i]="S3EC";
            i++;
        }if(y6.isSelected()){
            dept[i]="S3EEE";
            i++;
        }if(y7.isSelected()){
            dept[i]="S5CSA";
            i++;
            dept[i]="S3CSB";
            i++;
        }if(y8.isSelected()){
            dept[i]="S5EC";
            i++;
        }
        if(y9.isSelected()){
            dept[i]="S5EEE";
            i++;
        }
        if(y10.isSelected()){
            dept[i]="S7CS";
            i++;
        }
        if(y11.isSelected()){
            dept[i]="S7EC";
            i++;
        }if(y12.isSelected()){
            dept[i]="S7EEE";
            i++;
        }
        m=i;
        for(i=0;i<m;i++){
            System.out.println(dept[i]);
        }
}
    //To Find the total no Of benches used in the seat arrangement
    public void NoOfBench(){
    String url ="jdbc:mysql://localhost/sas?autoReconnect=true&serverTimezone=UTC&useSSL=False&allowPublicKeyRetrieval=true";
    bench=0;        
    try (Connection con = DriverManager.getConnection(url, "root", "")) {
                String sql1="SELECT * FROM `room`";
                PreparedStatement pst=con.prepareStatement(sql1);
                ResultSet rs=pst.executeQuery(sql1);
                while(rs.next()){
                    int i=0;
                    while(i<n){
                        String s=rs.getString(1);
                        if(rooms[i].equals(s)){
                            bench=bench+Integer.parseInt(rs.getString(2));
                            break;
                        }
                        i++;
                    }
                }
                System.out.println("No Of Benches"+bench);
            }catch (SQLException ex) {
            Logger.getLogger(Panel2.class.getName()).log(Level.SEVERE, null, ex);
        }    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        c10 = new javax.swing.JCheckBox();
        c11 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        y1 = new javax.swing.JCheckBox();
        y2 = new javax.swing.JCheckBox();
        y3 = new javax.swing.JCheckBox();
        y5 = new javax.swing.JCheckBox();
        y4 = new javax.swing.JCheckBox();
        y6 = new javax.swing.JCheckBox();
        y7 = new javax.swing.JCheckBox();
        y8 = new javax.swing.JCheckBox();
        y10 = new javax.swing.JCheckBox();
        y9 = new javax.swing.JCheckBox();
        y11 = new javax.swing.JCheckBox();
        y12 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton1.setText("ARRANGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setText("Rooms Used");

        c1.setText("411");

        c2.setText("412");

        c3.setText("413");

        c4.setText("422");

        c5.setText("202");

        c6.setText("201");

        c7.setText("601");

        c8.setText("603");

        c9.setText("604");
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        c10.setText("605");
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        c11.setText("drawing hall");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setText("Classes");

        y1.setText("1st CS");

        y2.setText("1st EC");

        y3.setText("1st EEE");

        y5.setText("2nd EC");

        y4.setText("2nd CS");

        y6.setText("2nd EEE");
        y6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed1(evt);
            }
        });

        y7.setText("3rd CS");
        y7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed1(evt);
            }
        });

        y8.setText("3rd EC");

        y10.setText("4th CS");

        y9.setText("3rd EEE");

        y11.setText("4th EC");

        y12.setText("4th EEE");

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Reload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(219, 219, 219))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(190, 190, 190))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c8, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(c1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(c10, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(c11, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addGap(61, 61, 61))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(c3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(c4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(c5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(c6, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(c7, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(y7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(y8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(y9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(y10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(y11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(y6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(y12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(y1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(y2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(y3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(y4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(y5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(y1)
                    .addComponent(y2)
                    .addComponent(y3)
                    .addComponent(y5)
                    .addComponent(y4)
                    .addComponent(y6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(y7)
                    .addComponent(y8)
                    .addComponent(y10)
                    .addComponent(y9)
                    .addComponent(y11)
                    .addComponent(y12))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            select();
            NoOfBench();
            String url ="jdbc:mysql://localhost/sas?autoReconnect=true&serverTimezone=UTC&useSSL=False&allowPublicKeyRetrieval=true";
            try (Connection con = DriverManager.getConnection(url, "root", "")) {
                String sql1="SELECT * FROM student";
                //department='cs' OR department='ec' ORDER BY department ASC 
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql1);
                int i=0;
                int c=0;
                do{
                    for(int j=0;j<bench;j++){
                        if(rs.next()){
                            for(int d=0;d<m;d++){
                                if (dept[d].equalsIgnoreCase(rs.getString(4))){
                                    arrange[j][i]=rs.getInt(1);
                                    break;
                                }
                            }
                            if(arrange[j][i]==0){
                                j--;
                            }
                        }
                        else{
                            c=1;
                            break;
                        }
                    }
                    i++;
                }while(c==0);
                flag=i;
                if(i>3){
                        JOptionPane.showMessageDialog(null, "arrangement not possible");
                    }
                for(int k=0;k<bench;k++){
                    for(int j=0;j<flag;j++){
                        System.out.print(arrange[k][j]+"    ");
                    }
                    System.out.println("");
                }
                ViewArrangement v=new ViewArrangement(arrange, rooms, bench);
                
//                String sql="SELECT * FROM student";
//                Statement st1=con.createStatement();
//                ResultSet rs1=st1.executeQuery(sql);                              
            }catch (SQLException ex) {
            Logger.getLogger(Pannel3.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed

    private void c6ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed1

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<rooms.length;i++){
            rooms[i]="";
           
        }
        y1.setSelected(false);
        y2.setSelected(false);
        y3.setSelected(false);
        y4.setSelected(false);
        y5.setSelected(false);
        y6.setSelected(false);
        y7.setSelected(false);
        y8.setSelected(false);
        y9.setSelected(false);
        y10.setSelected(false);
        y11.setSelected(false);
        y12.setSelected(false);
        for(int i=0;i<dept.length;i++){
            dept[i]="";
        }
        c1.setSelected(false);
        c2.setSelected(false);
        c3.setSelected(false);
        c4.setSelected(false);
        c5.setSelected(false);
        c6.setSelected(false);
        c7.setSelected(false);
        c8.setSelected(false);
        c9.setSelected(false);
        c10.setSelected(false);
        c11.setSelected(false);
        
        for(int k=0;k<bench;k++){
                    for(int j=0;j<flag;j++){
                        arrange[k][j]=0;
                    }
                }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox y1;
    private javax.swing.JCheckBox y10;
    private javax.swing.JCheckBox y11;
    private javax.swing.JCheckBox y12;
    private javax.swing.JCheckBox y2;
    private javax.swing.JCheckBox y3;
    private javax.swing.JCheckBox y4;
    private javax.swing.JCheckBox y5;
    private javax.swing.JCheckBox y6;
    private javax.swing.JCheckBox y7;
    private javax.swing.JCheckBox y8;
    private javax.swing.JCheckBox y9;
    // End of variables declaration//GEN-END:variables
}
